package com.chk.agentbrowser;
import androidx.test.platform.app.InstrumentationRegistry;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import org.junit.*;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import android.content.*;
import android.net.Uri;
import org.json.*;
import java.io.*;
import java.util.UUID;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;

/** End-to-end real encoder tests: source audio, frame effects, ratios and revision conflicts. */
@androidx.annotation.OptIn(markerClass={androidx.media3.common.util.UnstableApi.class,androidx.media3.common.util.ExperimentalApi.class})
@RunWith(AndroidJUnit4.class)
public final class VideoEditorIntegrationTest {
    private android.app.Instrumentation getInstrumentation(){return InstrumentationRegistry.getInstrumentation();}
    private Context context;private WorkspaceStore store;private String source;
    @Before public void setUp()throws Exception{context=getInstrumentation().getTargetContext();store=new WorkspaceStore(context);source="fixture-"+UUID.randomUUID()+".mov";File cache=new File(context.getCacheDir(),source);try(InputStream in=getInstrumentation().getContext().getAssets().open("editor-fixture.mp4");OutputStream out=new FileOutputStream(cache)){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);}store.importUri(Uri.fromFile(cache),source);cache.delete();}
    @After public void tearDown()throws Exception{store.file(source).delete();}
    private JSONObject invoke(String action,JSONObject args)throws Exception{CountDownLatch done=new CountDownLatch(1);AtomicReference<String> result=new AtomicReference<>();AtomicBoolean success=new AtomicBoolean();VideoEditorEngine.get().command(context,action,args,(ok,value)->{success.set(ok);result.set(value);done.countDown();});assertTrue("Command timed out",done.await(30,TimeUnit.SECONDS));assertTrue(result.get(),success.get());return new JSONObject(result.get());}
    private JSONObject project(String output)throws Exception{return new JSONObject().put("name","Encoder test").put("output",output).put("aspect_ratio","1:1").put("aspect_mode","fit").put("resolution",480).put("clips",new JSONArray().put(new JSONObject().put("path",source).put("start_ms",0).put("duration_ms",1000).put("filter","noir")).put(new JSONObject().put("path",source).put("start_ms",1000).put("duration_ms",1000).put("speed",2).put("text","CHK"))).put("audio",new JSONArray());}
    @Test public void testInspectAnyExtensionAndConsent()throws Exception{JSONObject info=MediaInspection.info(context,source);assertEquals(320,info.getInt("width"));assertEquals(2,info.getJSONArray("tracks").length());assertTrue(info.getLong("duration_ms")>=2900);assertTrue(MediaInspection.codecs().getJSONArray("codecs").length()>0);boolean previous=AgentClient.get(context).isPreviewAllowed();try{AgentClient.get(context).setPreviewAllowed(false);try{MediaInspection.frame(context,source,100);fail("Preview must require sharing consent");}catch(IOException expected){}AgentClient.get(context).setPreviewAllowed(true);JSONObject image=MediaInspection.frame(context,source,1000);assertTrue(android.util.Base64.decode(image.getString("jpeg_base64"),0).length>1000);assertTrue(image.getInt("width")<=640);}finally{AgentClient.get(context).setPreviewAllowed(previous);}}
    @Test public void testEmptyDraftAndRevisionGuard()throws Exception{JSONObject draft=new JSONObject().put("output","Draft-"+UUID.randomUUID()+".mp4").put("clips",new JSONArray()).put("audio",new JSONArray());JSONObject saved=invoke("video_editor_project_save",new JSONObject().put("project",draft));int revision=saved.getJSONObject("project").getInt("revision");CountDownLatch done=new CountDownLatch(1);AtomicBoolean success=new AtomicBoolean(true);VideoEditorEngine.get().command(context,"video_editor_project_save",new JSONObject().put("project",draft).put("expected_revision",revision-1),(ok,value)->{success.set(ok);done.countDown();});assertTrue(done.await(10,TimeUnit.SECONDS));assertFalse(success.get());assertEquals(revision,invoke("video_editor_project_read",new JSONObject()).getInt("revision"));}
    @Test public void testRealExportPreservesAudioAndAppliesRatioAndSpeed()throws Exception{String output="export-"+UUID.randomUUID()+".mp4";invoke("video_editor_project_save",new JSONObject().put("project",project(output)));invoke("video_editor_export",new JSONObject());String state="";for(int i=0;i<360;i++){JSONObject status=invoke("video_editor_status",new JSONObject());state=status.getString("state");if(!state.equals("running")&&!state.equals("preparing"))break;Thread.sleep(500);}assertEquals(VideoEditorEngine.get().status().toString(),"completed",state);JSONObject verified=invoke("video_editor_verify_output",new JSONObject());assertTrue(verified.toString(),verified.getBoolean("valid"));assertEquals("480",verified.getString("width_px"));assertEquals("480",verified.getString("height_px"));assertTrue(verified.getBoolean("has_audio"));assertTrue(Math.abs(verified.getLong("duration_ms")-1500)<300);assertEquals(1500,verified.getLong("expected_duration_ms"));
        JSONObject changed=project("future-"+UUID.randomUUID()+".mp4").put("aspect_ratio","16:9");invoke("video_editor_project_save",new JSONObject().put("project",changed));JSONObject original=invoke("video_editor_verify_output",new JSONObject());assertEquals(output,original.getString("output"));assertTrue(original.getBoolean("valid"));store.file(output).delete();}
    private void awaitExport()throws Exception{String state="";for(int i=0;i<480;i++){JSONObject current=invoke("video_editor_status",new JSONObject());state=current.getString("state");if(!state.equals("running")&&!state.equals("preparing"))break;Thread.sleep(500);}assertEquals(VideoEditorEngine.get().status().toString(),"completed",state);}
    @Test public void testCompleteSevenClipPortraitExportAndReplacement()throws Exception{
        String output="complete-"+UUID.randomUUID()+".mp4";JSONObject p=project(output).put("aspect_ratio","9:16");JSONArray clips=new JSONArray();for(int i=0;i<7;i++)clips.put(new JSONObject().put("path",source).put("start_ms",0).put("duration_ms",3000).put("text",i==0?"Projet complet":""));JSONArray tracks=new JSONArray();for(int i=0;i<7;i++)tracks.put(new JSONObject().put("path",source).put("start_ms",0).put("duration_ms",3000));p.put("clips",clips).put("audio",tracks).put("mute_original",true);invoke("video_editor_project_save",new JSONObject().put("project",p));
        try(FileOutputStream old=new FileOutputStream(store.file(output))){old.write("Old completed video must survive a rejected export".getBytes("UTF-8"));}long oldSize=store.file(output).length();CountDownLatch rejected=new CountDownLatch(1);AtomicBoolean accepted=new AtomicBoolean(true);VideoEditorEngine.get().command(context,"video_editor_export",new JSONObject(),(ok,res)->{accepted.set(ok);rejected.countDown();});assertTrue(rejected.await(30,TimeUnit.SECONDS));assertFalse(accepted.get());assertEquals(oldSize,store.file(output).length());
        invoke("video_editor_export",new JSONObject().put("replace",true));awaitExport();JSONObject verified=invoke("video_editor_verify_output",new JSONObject());assertTrue(verified.toString(),verified.getBoolean("valid"));assertEquals(21000,verified.getLong("expected_duration_ms"));assertTrue(Math.abs(21000-verified.getLong("duration_ms"))<500);assertTrue(verified.getBoolean("has_audio"));assertEquals("480",verified.getString("width_px"));assertTrue(Integer.parseInt(verified.getString("height_px"))>850);store.file(output).delete();
    }
    @Test public void testExportDialogOffersReplacementAndCopy()throws Exception{
        String output="dialog-"+UUID.randomUUID()+".mp4";try(FileOutputStream old=new FileOutputStream(store.file(output))){old.write(new byte[1024]);}invoke("video_editor_project_save",new JSONObject().put("project",project(output)));
        VideoEditorActivity activity=(VideoEditorActivity)getInstrumentation().startActivitySync(new Intent(context,VideoEditorActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(1500);getInstrumentation().runOnMainSync(()->activity.getWindow().getDecorView().findViewWithTag("export_project").performClick());boolean choices=false;for(int i=0;i<30;i++){android.view.accessibility.AccessibilityNodeInfo root=getInstrumentation().getUiAutomation().getRootInActiveWindow();if(root!=null&&!root.findAccessibilityNodeInfosByText("Nouvelle copie").isEmpty()&&!root.findAccessibilityNodeInfosByText("Remplacer").isEmpty()){choices=true;root.findAccessibilityNodeInfosByText("Annuler").get(0).performAction(android.view.accessibility.AccessibilityNodeInfo.ACTION_CLICK);break;}Thread.sleep(200);}assertTrue("Both export choices must be reachable",choices);getInstrumentation().runOnMainSync(()->activity.finish());assertEquals(1024,store.file(output).length());store.file(output).delete();
    }
    @Test public void testCatalogCopyAndRatioValidation()throws Exception{String folder="catalog-"+UUID.randomUUID();store.mkdir(folder);String destination=folder+"/duplicate.mov";WorkspaceCatalog.copy(context,source,destination);assertEquals(store.file(source).length(),store.file(destination).length());JSONObject catalog=WorkspaceCatalog.query(context,folder,"video","","date",0);assertEquals(1,catalog.getJSONArray("items").length());assertEquals(1,catalog.getJSONObject("counts").getInt("video"));try{WorkspaceCatalog.copy(context,source,destination);fail("Copy must refuse overwrite");}catch(IOException expected){}assertEquals(16f/9f,VideoEditorEngine.ratio("16:9"),0.0001f);assertEquals(2.35f,VideoEditorEngine.ratio("2.35:1"),0.0001f);try{VideoEditorEngine.ratio("NaN:1");fail("NaN ratio accepted");}catch(IllegalArgumentException expected){}store.file(destination).delete();store.file(folder).delete();}
    @Test public void testStudioAndMobileLayoutSnapshots()throws Exception{context.getSharedPreferences("update_monitor",0).edit().putBoolean("enabled",false).commit();MainActivity main=(MainActivity)getInstrumentation().startActivitySync(new Intent(context,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));getInstrumentation().waitForIdleSync();getInstrumentation().runOnMainSync(()->main.findViewById(R.id.back).performClick());Thread.sleep(1500);snapshot(main,"browser");getInstrumentation().runOnMainSync(()->main.findViewById(R.id.nav_files).performClick());Thread.sleep(1000);snapshot(main,"files");getInstrumentation().runOnMainSync(()->main.finish());invoke("video_editor_project_save",new JSONObject().put("project",project("UI-"+UUID.randomUUID()+".mp4")));VideoEditorActivity studio=(VideoEditorActivity)getInstrumentation().startActivitySync(new Intent(context,VideoEditorActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(1500);
        java.lang.reflect.Field preview=VideoEditorActivity.class.getDeclaredField("player");preview.setAccessible(true);androidx.media3.transformer.CompositionPlayer player=(androidx.media3.transformer.CompositionPlayer)preview.get(studio);AtomicInteger playback=new AtomicInteger();for(int i=0;i<80;i++){getInstrumentation().runOnMainSync(()->playback.set(player.getPlaybackState()));if(playback.get()==androidx.media3.common.Player.STATE_READY)break;Thread.sleep(250);}assertEquals("Composition preview must be ready",androidx.media3.common.Player.STATE_READY,playback.get());
        snapshot(studio,"studio");getInstrumentation().runOnMainSync(()->studio.finish());}
    private void snapshot(android.app.Activity activity,String name)throws Exception{
        getInstrumentation().waitForIdleSync();android.graphics.Bitmap image=getInstrumentation().getUiAutomation().takeScreenshot();assertNotNull("Screenshot missing",image);try(OutputStream out=new FileOutputStream(new File(context.getCacheDir(),"qa-"+name+".png"))){image.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}image.recycle();
    }
}
