package com.chk.agentbrowser;
import android.app.Activity;
import android.graphics.Typeface;
import android.text.*;
import android.text.style.ForegroundColorSpan;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import java.util.*;

/** Fast native new tab; actual Google and other pages remain visible during MCP work. */
final class BrowserHome {
    interface Navigate{void open(String value);}
    private final Activity a;private final EditText address;private final BrowserStore store;private final Navigate navigate;
    private final FrameLayout home,suggestions;private boolean browser=true,webVisible;private String drawn="";
    BrowserHome(Activity a,EditText input,BrowserStore store,Navigate navigate){this.a=a;address=input;this.store=store;this.navigate=navigate;home=a.findViewById(R.id.start_page);suggestions=a.findViewById(R.id.search_suggestions);
        input.setOnFocusChangeListener((v,focus)->{if(focus&&browser)drawSuggestions();else suggestions.setVisibility(View.GONE);});
        input.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int st,int before,int count){if(input.hasFocus()&&browser)drawSuggestions();}public void afterTextChanged(Editable e){}});
    }
    boolean isHome(String url){return url==null||url.equals("https://www.google.com")||url.equals("https://www.google.com/");}
    void revealWeb(){webVisible=true;home.setVisibility(View.GONE);closeSuggestions();address.clearFocus();}
    void newStart(){webVisible=false;drawn="";}
    void space(boolean active,String url){browser=active;page(url);if(!active)suggestions.setVisibility(View.GONE);}
    void page(String url){boolean show=browser&&isHome(url)&&!webVisible;home.setVisibility(show?View.VISIBLE:View.GONE);if(show){String key=store.get("history").toString()+store.get("favorites").toString();if(!key.equals(drawn)||home.getChildCount()==0){drawHome();drawn=key;}if(!address.hasFocus())address.setText("google.com");}if(!isHome(url))suggestions.setVisibility(View.GONE);}
    private int dp(int value){return MobileUi.dp(a,value);}
    private TextView flat(String text,int size,int color){TextView v=MobileUi.text(a,text,size,color);v.setPadding(dp(8),dp(8),dp(8),dp(8));return v;}
    private void drawHome(){home.removeAllViews();ScrollView scroll=new ScrollView(a);scroll.setFillViewport(false);home.addView(scroll);LinearLayout content=MobileUi.column(a);content.setPadding(dp(16),dp(12),dp(16),dp(18));scroll.addView(content);
        TextView brand=flat("Google",46,MobileUi.TEXT);brand.setGravity(Gravity.CENTER);brand.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));SpannableString word=new SpannableString("Google");int[] colors={0xff4285f4,0xffea4335,0xfffbbc05,0xff4285f4,0xff34a853,0xffea4335};for(int i=0;i<6;i++)word.setSpan(new ForegroundColorSpan(colors[i]),i,i+1,0);brand.setText(word);content.addView(brand,new LinearLayout.LayoutParams(-1,dp(86)));
        LinearLayout search=new LinearLayout(a);search.setGravity(Gravity.CENTER_VERTICAL);search.setBackground(MobileUi.bg(a,0xff30333f));content.addView(search,new LinearLayout.LayoutParams(-1,dp(56)));
        TextView g=flat("G",26,0xff4285f4);g.setTypeface(null,Typeface.BOLD);search.addView(g,new LinearLayout.LayoutParams(dp(44),-1));TextView input=flat("Rechercher sur Google",16,0xffe3e3e8);input.setSingleLine(true);search.addView(input,new LinearLayout.LayoutParams(0,-1,1));View.OnClickListener focus=v->{address.setText("");address.requestFocus();((InputMethodManager)a.getSystemService(Activity.INPUT_METHOD_SERVICE)).showSoftInput(address,InputMethodManager.SHOW_IMPLICIT);};search.setOnClickListener(focus);input.setOnClickListener(focus);
        ImageView mic=new ImageView(a);mic.setImageResource(R.drawable.ic_mic);mic.setPadding(dp(12),dp(12),dp(12),dp(12));mic.setContentDescription("Recherche vocale");search.addView(mic,new LinearLayout.LayoutParams(dp(48),-1));mic.setOnClickListener(v->a.findViewById(R.id.voice_search).performClick());
        LinearLayout quickActions=new LinearLayout(a);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(58));ap.topMargin=dp(8);content.addView(quickActions,ap);
        TextView history=flat("◷  Historique",14,MobileUi.TEXT),favorites=flat("☆  Favoris",14,MobileUi.TEXT);for(TextView v:new TextView[]{history,favorites}){v.setGravity(Gravity.CENTER);v.setBackground(MobileUi.bg(a,0xff292c35));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(44),1);lp.setMargins(dp(3),dp(4),dp(3),dp(4));quickActions.addView(v,lp);}history.setOnClickListener(v->showStored("history"));favorites.setOnClickListener(v->showStored("favorites"));
        String[] names={"Google","YouTube","ChatGPT","GitHub"},urls={"https://www.google.com","https://www.youtube.com","https://chatgpt.com","https://github.com"};int[] siteIcons={R.drawable.site_google,R.drawable.site_youtube,R.drawable.site_chatgpt,R.drawable.site_github};LinearLayout quick=new LinearLayout(a);content.addView(quick);for(int i=0;i<names.length;i++){String target=urls[i];LinearLayout cell=MobileUi.column(a);cell.setGravity(Gravity.CENTER);quick.addView(cell,new LinearLayout.LayoutParams(0,dp(92),1));ImageView icon=new ImageView(a);icon.setImageResource(siteIcons[i]);icon.setScaleType(ImageView.ScaleType.FIT_CENTER);icon.setPadding(dp(10),dp(10),dp(10),dp(10));icon.setBackground(MobileUi.bg(a,0xff262930));cell.addView(icon,new LinearLayout.LayoutParams(dp(56),dp(54)));TextView label=flat(names[i],12,MobileUi.TEXT);label.setGravity(Gravity.CENTER);cell.addView(label);cell.setOnClickListener(v->{if(target.equals(urls[0]))revealWeb();navigate.open(target);});}
        JSONArray entries=store.get("history");ArrayList<JSONObject> unique=new ArrayList<>();Set<String> seen=new HashSet<>();for(int i=0;i<entries.length()&&unique.size()<4;i++){JSONObject item=entries.optJSONObject(i);if(item!=null&&!isHome(item.optString("url"))&&seen.add(item.optString("url")))unique.add(item);}
        if(!unique.isEmpty()){section(content,"Reprendre la navigation");for(int i=0;i<unique.size();i+=2){LinearLayout row=new LinearLayout(a);content.addView(row);for(int j=i;j<i+2&&j<unique.size();j++)historyCard(row,unique.get(j));if(i+1==unique.size())row.addView(new View(a),new LinearLayout.LayoutParams(0,1,1));}}
        JSONArray pinned=store.get("favorites");if(pinned.length()>0){section(content,"Tes favoris");for(int i=0;i<Math.min(3,pinned.length());i++){JSONObject item=pinned.optJSONObject(i);if(item!=null)link(content,"☆  "+displayTitle(item),item.optString("url"));}}
        section(content,"À découvrir");discovery(content,"Explorer l’univers","Images et découvertes · NASA","https://www.nasa.gov/images/","✦");discovery(content,"Actualités et recherches","Ouvrir Google Actualités","https://news.google.com/","▤");
    }
    private void section(LinearLayout content,String title){TextView t=flat(title,17,MobileUi.TEXT);t.setTypeface(null,Typeface.BOLD);content.addView(t);}
    private void discovery(LinearLayout parent,String title,String subtitle,String url,String icon){LinearLayout row=new LinearLayout(a);row.setGravity(Gravity.CENTER_VERTICAL);row.setBackground(MobileUi.bg(a,0xff272a32));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(82));lp.bottomMargin=dp(8);parent.addView(row,lp);TextView art=flat(icon,38,0xffa8b7ff);art.setGravity(Gravity.CENTER);row.addView(art,new LinearLayout.LayoutParams(dp(66),-1));LinearLayout text=MobileUi.column(a);row.addView(text,new LinearLayout.LayoutParams(0,-2,1));text.addView(flat(title,15,MobileUi.TEXT));text.addView(flat(subtitle,12,0xffbdc1c6));row.setOnClickListener(v->navigate.open(url));}
    private void historyCard(LinearLayout row,JSONObject item){LinearLayout card=MobileUi.column(a);card.setBackground(MobileUi.bg(a,0xff292c34));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(106),1);lp.setMargins(dp(3),dp(4),dp(3),dp(4));row.addView(card,lp);TextView title=flat(displayTitle(item),15,MobileUi.TEXT);title.setMaxLines(2);card.addView(title,new LinearLayout.LayoutParams(-1,0,1));String host=android.net.Uri.parse(item.optString("url")).getHost();TextView domain=flat(host==null?"Page web":host.replaceFirst("^www\\.",""),12,0xffbdc1c6);domain.setSingleLine(true);card.addView(domain);card.setOnClickListener(v->navigate.open(item.optString("url")));}
    private String displayTitle(JSONObject item){String url=item.optString("url");try{android.net.Uri parsed=android.net.Uri.parse(url);String host=parsed.getHost(),query=parsed.getQueryParameter("q");if(host!=null&&(host.equals("google.com")||host.endsWith(".google.com"))&&query!=null&&!query.isEmpty())return query;}catch(Exception ignored){}return item.optString("title",url);}
    private void showStored(String key){JSONArray items=store.get(key);if(items.length()==0){android.widget.Toast.makeText(a,key.equals("history")?"Aucune page visitée":"Aucun favori enregistré",android.widget.Toast.LENGTH_SHORT).show();return;}String[] labels=new String[items.length()];for(int i=0;i<labels.length;i++)labels[i]=displayTitle(items.optJSONObject(i));new android.app.AlertDialog.Builder(a).setTitle(key.equals("history")?"Historique":"Favoris").setItems(labels,(d,n)->navigate.open(items.optJSONObject(n).optString("url"))).setNegativeButton("Fermer",null).show();}
    private void link(LinearLayout parent,String label,String url){TextView v=flat(label,15,MobileUi.TEXT);v.setMinHeight(dp(52));v.setMaxLines(2);parent.addView(v);v.setOnClickListener(w->navigate.open(url));}
    private void drawSuggestions(){suggestions.removeAllViews();suggestions.setVisibility(View.VISIBLE);ScrollView sc=new ScrollView(a);suggestions.addView(sc);LinearLayout rows=MobileUi.column(a);rows.setPadding(dp(12),dp(8),dp(12),0);sc.addView(rows);String query=address.getText().toString().trim();if(!query.isEmpty())link(rows,"⌕   Rechercher « "+query+" »",query);
        JSONArray history=store.get("history");int added=0;for(int i=0;i<history.length()&&added<10;i++){JSONObject item=history.optJSONObject(i);if(item==null)continue;String title=displayTitle(item),url=item.optString("url");if(!isHome(url)&&(query.isEmpty()||(title+url).toLowerCase(Locale.ROOT).contains(query.toLowerCase(Locale.ROOT)))){link(rows,"◷   "+title,url);added++;}}
        if(added==0)rows.addView(flat("Les pages visitées apparaîtront ici.",14,0xffbdc1c6));TextView close=flat("Fermer la recherche",15,0xffa8b7ff);close.setMinHeight(dp(48));rows.addView(close);close.setOnClickListener(v->{address.clearFocus();closeSuggestions();((InputMethodManager)a.getSystemService(Activity.INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(address.getWindowToken(),0);});
    }
    boolean closeSuggestions(){boolean open=suggestions.getVisibility()==View.VISIBLE;suggestions.setVisibility(View.GONE);return open;}
    void destroy(){suggestions.removeAllViews();home.removeAllViews();}
}
