package com.chk.agentbrowser;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.os.*;
import android.provider.OpenableColumns;
import android.view.*;
import android.widget.*;
import androidx.media3.common.Player;
import androidx.media3.transformer.CompositionPlayer;
import androidx.media3.transformer.Composition;
import org.json.*;
import java.util.*;

/** Thumb-friendly studio: live composition preview, tracks, real edits and local MP4 export. */
@androidx.annotation.OptIn(markerClass={androidx.media3.common.util.UnstableApi.class,androidx.media3.common.util.ExperimentalApi.class})
public final class VideoEditorActivity extends Activity {
    private final VideoEditorEngine engine=VideoEditorEngine.get();
    private final Handler ui=new Handler(Looper.getMainLooper());
    private final ArrayDeque<String> undo=new ArrayDeque<>(),redo=new ArrayDeque<>();
    private JSONObject project;
    private LinearLayout tools;
    private StudioTimeline timeline;
    private TextView quality,scope;
    private boolean importing;
    private boolean compact;
    private long lastProjectCheck;
    private boolean primingPreview;
    private float previewVolume=1;
    private TextView title,clock,status,play,format;

    private androidx.media3.ui.PlayerView viewer;
    private CompositionPlayer player;
    private boolean alive,scrubbing,saving;
    private int selected,previewGeneration,revision;
    private String importKind="video",exportCopyPath="";
    private final Runnable ticker=new Runnable(){public void run(){
        if(!alive)return;
        if(player!=null&&!scrubbing){long pos=player.getCurrentPosition();timeline.position(pos);String value=time(pos)+" / "+time(total());if(!clock.getText().toString().equals(value))clock.setText(value);String icon=player.isPlaying()?"Ⅱ":"▶";if(!play.getText().toString().equals(icon))play.setText(icon);}
        long now=android.os.SystemClock.elapsedRealtime();if(!saving&&!importing&&project!=null&&now-lastProjectCheck>2500){lastProjectCheck=now;engine.command(VideoEditorActivity.this,"video_editor_project_read",new JSONObject(),(ok,value)->ui.post(()->{if(!alive||saving||importing||!ok)return;try{JSONObject fresh=new JSONObject(value);if(fresh.optInt("revision")!=revision){project=fresh;revision=fresh.optInt("revision");undo.clear();redo.clear();draw();preview();}}catch(Exception ignored){}}));}
        JSONObject s=engine.status();String state=s.optString("state");
        status.setVisibility(importing||state.equals("running")||state.equals("preparing")||state.equals("failed")||state.equals("completed")?View.VISIBLE:View.GONE);
        status.setText(importing?"Importation des médias…":"running".equals(state)?"Export MP4 · "+s.optInt("progress_percent")+" %":"preparing".equals(state)?"Préparation du rendu…":"completed".equals(state)?"Export terminé · toucher pour lire / partager":"failed".equals(state)?"Export impossible : "+s.optString("error"):"Montage local · sauvegarde automatique");
        ui.postDelayed(this,player!=null&&player.isPlaying()?33:600);
    }};
    @Override public void onCreate(Bundle state){super.onCreate(state);alive=true;if(state!=null)exportCopyPath=state.getString("export_copy_path","");
        getWindow().setStatusBarColor(0xff111111);getWindow().setNavigationBarColor(0xff111111);
        compact=getResources().getDisplayMetrics().heightPixels/getResources().getDisplayMetrics().density<720;
        LinearLayout root=MobileUi.column(this);root.setBackgroundColor(0xff111214);setContentView(root);
        LinearLayout header=new LinearLayout(this);header.setPadding(dp(6),0,dp(8),0);header.setGravity(Gravity.CENTER_VERTICAL);root.addView(header,new LinearLayout.LayoutParams(-1,dp(compact?48:54)));
        TextView close=chip("×");close.setTextSize(26);close.setContentDescription("Fermer le montage");header.addView(close,new LinearLayout.LayoutParams(dp(42),-1));close.setOnClickListener(v->finish());
        title=MobileUi.text(this,"Studio ▾",13,MobileUi.TEXT);title.setPadding(dp(3),0,dp(3),0);title.setSingleLine(true);title.setEllipsize(android.text.TextUtils.TruncateAt.END);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));title.setOnClickListener(v->projectMenu());
        quality=chip("720p ▾");quality.setTextSize(12);quality.setBackground(MobileUi.bg(this,0xff292b30));header.addView(quality,new LinearLayout.LayoutParams(dp(64),dp(40)));quality.setOnClickListener(v->qualityMenu());
        TextView export=chip("Exporter");export.setTag("export_project");export.setTextSize(13);export.setTextColor(0xff061a18);export.setTypeface(null,android.graphics.Typeface.BOLD);export.setBackground(MobileUi.bg(this,0xff20d4d3));LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(dp(84),dp(40));ep.leftMargin=dp(6);header.addView(export,ep);export.setOnClickListener(v->export());
        FrameLayout canvas=new FrameLayout(this);canvas.setBackgroundColor(0xff000000);root.addView(canvas,new LinearLayout.LayoutParams(-1,0,1));viewer=(androidx.media3.ui.PlayerView)getLayoutInflater().inflate(R.layout.studio_player,canvas,false);canvas.addView(viewer,new FrameLayout.LayoutParams(-1,-1));
        TextView empty=MobileUi.text(this,"＋\nAjouter une vidéo",17,MobileUi.MUTED);empty.setGravity(Gravity.CENTER);empty.setTag("empty");canvas.addView(empty,new FrameLayout.LayoutParams(-1,-1));empty.setOnClickListener(v->addMenu("video"));
        player=new CompositionPlayer.Builder(this).build();viewer.setPlayer(player);
        player.addListener(new Player.Listener(){@Override public void onRenderedFirstFrame(){if(primingPreview){primingPreview=false;player.pause();player.setVolume(previewVolume);}}@Override public void onPlayerError(androidx.media3.common.PlaybackException error){toast("Aperçu indisponible : "+error.getErrorCodeName());}});
        LinearLayout playback=new LinearLayout(this);playback.setPadding(dp(8),0,dp(4),0);playback.setGravity(Gravity.CENTER_VERTICAL);root.addView(playback,new LinearLayout.LayoutParams(-1,dp(48)));
        clock=MobileUi.text(this,"00:00 / 00:00",11,0xffc0c3cc);clock.setPadding(dp(4),0,0,0);playback.addView(clock,new LinearLayout.LayoutParams(0,-2,1));
        play=chip("▶");playback.addView(play,new LinearLayout.LayoutParams(dp(48),-1));play.setOnClickListener(v->{if(primingPreview){primingPreview=false;player.setVolume(previewVolume);player.play();return;}if(player.isPlaying())player.pause();else{if(player.getPlaybackState()==Player.STATE_ENDED)player.seekTo(0);player.play();}});
        format=chip("9:16");format.setTextSize(11);format.setContentDescription("Format du montage");playback.addView(format,new LinearLayout.LayoutParams(dp(44),dp(38)));format.setOnClickListener(v->ratioMenu());
        TextView un=chip("↶");un.setContentDescription("Annuler la dernière modification");playback.addView(un,new LinearLayout.LayoutParams(dp(40),-1));un.setOnClickListener(v->history(false));
        TextView re=chip("↷");re.setContentDescription("Rétablir la modification");playback.addView(re,new LinearLayout.LayoutParams(dp(40),-1));re.setOnClickListener(v->history(true));
        HorizontalScrollView tracks=new HorizontalScrollView(this);tracks.setHorizontalScrollBarEnabled(false);root.addView(tracks,new LinearLayout.LayoutParams(-1,dp(compact?120:156)));timeline=new StudioTimeline(this);tracks.addView(timeline,new android.widget.FrameLayout.LayoutParams(-2,-1));timeline.setListener(new StudioTimeline.Listener(){public void seek(long position,int clip){selected=clip;player.pause();player.seekTo(position);clock.setText(time(position)+" / "+time(total()));}public void scrubbing(boolean active){player.setScrubbingModeEnabled(active);}});
        LinearLayout summary=new LinearLayout(this);summary.setGravity(Gravity.CENTER_VERTICAL);root.addView(summary,new LinearLayout.LayoutParams(-1,dp(38)));scope=MobileUi.text(this,"Projet complet",11,0xffaeb4c1);scope.setPadding(dp(10),0,0,0);summary.addView(scope,new LinearLayout.LayoutParams(0,-2,1));TextView add=chip("＋ Vidéo");add.setTextSize(12);summary.addView(add,new LinearLayout.LayoutParams(dp(82),-1));add.setOnClickListener(v->addMenu("video"));
        LinearLayout mainTools=new LinearLayout(this);root.addView(mainTools,new LinearLayout.LayoutParams(-1,dp(compact?56:64)));
        mainTool(mainTools,"Éditer","scissors",()->editMenu());mainTool(mainTools,"Audio","audio",()->audioMenu());mainTool(mainTools,"Texte","text",()->{if(editable())caption();});mainTool(mainTools,"Effets","effects",()->{if(editable())filter();});mainTool(mainTools,"Plans","layers",()->clipMenu());mainTool(mainTools,"Format","crop",()->ratioMenu());
        HorizontalScrollView strip=new HorizontalScrollView(this);strip.setHorizontalScrollBarEnabled(false);root.addView(strip,new LinearLayout.LayoutParams(-1,dp(compact?44:48)));tools=new LinearLayout(this);strip.addView(tools);
        tool("✂","Diviser",()->split());tool("◷","Vitesse",()->speed());tool("▣","Recadrer",()->ratioMenu());tool("↻","Rotation",()->rotation());tool("⇄","Déplacer",()->move());tool("▣","Dupliquer",()->duplicate());tool("×","Supprimer",()->delete(false,selected));
        status=MobileUi.text(this,"Montage local",11,MobileUi.MUTED);status.setPadding(dp(10),dp(2),dp(10),dp(2));status.setMaxLines(2);root.addView(status,new LinearLayout.LayoutParams(-1,dp(34)));status.setOnClickListener(v->outputMenu());scope.setOnClickListener(v->outputMenu());
        engine.command(this,"video_editor_project_read",new JSONObject(),(ok,res)->runOnUiThread(()->{try{if(ok){project=new JSONObject(res);revision=project.optInt("revision",0);draw();preview();String launch=getIntent().getStringExtra("add_path");if(launch!=null)addFile("video",launch);}else toast(res);}catch(Exception e){toast(e.getMessage());}}));ui.post(ticker);
    }
    private int dp(int n){return MobileUi.dp(this,n);}
    private TextView chip(String text){TextView v=MobileUi.text(this,text,15,MobileUi.TEXT);v.setMinHeight(dp(48));v.setMinWidth(dp(48));v.setGravity(Gravity.CENTER);v.setFocusable(true);return v;}
    private void mainTool(LinearLayout parent,String label,String icon,Runnable action){TextView view=UiIcons.button(this,label,icon,0xfff4f4ff);parent.addView(view,new LinearLayout.LayoutParams(0,-1,1));view.setOnClickListener(v->action.run());}
    private void editMenu(){if(!editable())return;new AlertDialog.Builder(this).setTitle("Éditer le plan "+(selected+1)).setItems(new String[]{"Découper avec les curseurs","Diviser au curseur","Vitesse","Rotation","Son du plan"},(d,n)->{switch(n){case 0:trim(false,selected);break;case 1:split();break;case 2:speed();break;case 3:rotation();break;case 4:mute();break;}}).show();}
    private void audioMenu(){new AlertDialog.Builder(this).setTitle("Audio").setItems(new String[]{"Ajouter un audio","Son original","Modifier les pistes"},(d,n)->{if(n==0)addMenu("audio");else if(n==1)mute();else{String[] names=new String[audio().length()];for(int i=0;i<names.length;i++)names[i]=name(audio().optJSONObject(i).optString("path"));new AlertDialog.Builder(this).setTitle("Pistes audio").setItems(names,(x,i)->new AlertDialog.Builder(this).setItems(new String[]{"Découper","Supprimer"},(y,j)->{if(j==0)trim(true,i);else delete(true,i);}).show()).show();}}).show();}
    private void clipMenu(){if(!editable())return;new AlertDialog.Builder(this).setTitle("Plans du montage").setItems(new String[]{"Ajouter une vidéo","Dupliquer le plan","Déplacer le plan","Supprimer le plan"},(d,n)->{switch(n){case 0:addMenu("video");break;case 1:duplicate();break;case 2:move();break;case 3:delete(false,selected);break;}}).show();}
    private void tool(String glyph,String label,Runnable action){TextView v=chip(glyph+"  "+label);v.setTextSize(12);v.setPadding(dp(10),0,dp(10),0);v.setMinHeight(dp(44));v.setSingleLine(true);tools.addView(v,new LinearLayout.LayoutParams(-2,dp(compact?44:48)));v.setOnClickListener(w->{if(editable())action.run();});}
    private void toast(String text){if(alive)Toast.makeText(this,text,Toast.LENGTH_LONG).show();}
    private JSONArray clips(){return project==null?new JSONArray():project.optJSONArray("clips");}
    private JSONArray audio(){if(project==null)return new JSONArray();JSONArray a=project.optJSONArray("audio");return a==null?new JSONArray():a;}
    private JSONObject clip(){return clips().optJSONObject(selected);}
    private long length(JSONObject c){return Math.round(c.optLong("duration_ms",10000)/c.optDouble("speed",1));}
    private long total(){long sum=0;for(int i=0;i<clips().length();i++)sum+=length(clips().optJSONObject(i));return sum;}
    private long start(int index){long sum=0;for(int i=0;i<index;i++)sum+=length(clips().optJSONObject(i));return sum;}
    private String time(long ms){return String.format(Locale.ROOT,"%02d:%02d.%01d",ms/60000,(ms/1000)%60,(ms%1000)/100);}
    private String name(String path){return path.substring(path.lastIndexOf('/')+1);}
    private boolean editable(){if(project==null||saving||importing){toast("Sauvegarde en cours…");return false;}String s=engine.status().optString("state");if(s.equals("running")||s.equals("preparing")){toast("Attends la fin de l’export ou annule-le");return false;}if(clip()==null){toast("Ajoute puis sélectionne une vidéo");return false;}return true;}
    private void remember(){undo.addLast(project.toString());while(undo.size()>30)undo.removeFirst();redo.clear();}
    private void draw(){if(!alive||project==null)return;title.setText(project.optString("name","Studio")+" ▾");format.setText(project.optString("aspect_ratio","source").replace("source","Original"));quality.setText(project.optInt("resolution",720)+"p ▾");scope.setText("✓ Projet complet · "+time(total()));selected=Math.max(0,Math.min(selected,clips().length()-1));timeline.setProject(project,selected);clock.setText(time(player.getCurrentPosition())+" / "+time(total()));((ViewGroup)viewer.getParent()).findViewWithTag("empty").setVisibility(clips().length()==0?View.VISIBLE:View.GONE);}
    private void save(){saving=true;String fallback=undo.peekLast();JSONObject snapshot;try{snapshot=new JSONObject(project.toString());}catch(Exception e){return;}
        engine.command(this,"video_editor_project_save",new JSONObjectSafe("project",snapshot).withRevision(revision),(ok,res)->ui.post(()->{saving=false;if(!alive)return;if(ok){try{revision=new JSONObject(res).getJSONObject("project").optInt("revision");project.put("revision",revision);}catch(Exception ignored){}draw();preview();}else{toast(res);try{if(fallback!=null)project=new JSONObject(fallback);}catch(Exception ignored){}draw();}}));
    }
    private void preview(){if(clips().length()==0){player.stop();return;}int generation=++previewGeneration;long position=player.getCurrentPosition();boolean playing=player.isPlaying();String snapshot=project.toString();WorkspaceCommands.IO.execute(()->{try{Composition composition=engine.composition(this,new JSONObject(snapshot));ui.post(()->{if(!alive||generation!=previewGeneration)return;try{player.setComposition(composition,Math.min(position,Math.max(0,total()-1)));player.prepare();if(!playing){if(!primingPreview)previewVolume=player.getVolume();primingPreview=true;player.setVolume(0);}player.setPlayWhenReady(true);}catch(Exception e){toast("Aperçu : "+e.getMessage());}});}catch(Exception e){ui.post(()->toast(e.getMessage()));}});}
    private void history(boolean forward){if(saving||project==null)return;ArrayDeque<String> from=forward?redo:undo,to=forward?undo:redo;if(from.isEmpty())return;try{to.addLast(project.toString());project=new JSONObject(from.removeLast());save();}catch(Exception e){toast(e.getMessage());}}
    private void put(JSONObject object,String key,Object value){try{remember();object.put(key,value);save();}catch(Exception e){toast(e.getMessage());}}
    private void split(){if(clip()==null)return;JSONObject c=clip();long cut=Math.round((player.getCurrentPosition()-start(selected))*c.optDouble("speed",1)),duration=c.optLong("duration_ms");if(cut<500||duration-cut<500){toast("Place le curseur au milieu du plan (minimum 0,5 s par partie)");return;}
        try{remember();JSONObject second=new JSONObject(c.toString());second.put("start_ms",c.optLong("start_ms")+cut).put("duration_ms",duration-cut);c.put("duration_ms",cut);JSONArray out=new JSONArray();for(int i=0;i<clips().length();i++){out.put(clips().get(i));if(i==selected)out.put(second);}project.put("clips",out);save();}catch(Exception e){toast(e.getMessage());}}
    private void trim(boolean sound,int index){JSONObject c=(sound?audio():clips()).optJSONObject(index);if(c==null||saving||importing)return;String path=c.optString("path");WorkspaceCommands.IO.execute(()->{try{long sourceDuration=MediaInspection.info(this,path).optLong("duration_ms");ui.post(()->{if(!alive)return;LinearLayout box=MobileUi.column(this);box.setPadding(dp(20),dp(10),dp(20),dp(12));TextView bounds=MobileUi.text(this,"",14,MobileUi.TEXT);box.addView(bounds);SeekBar begin=new SeekBar(this),end=new SeekBar(this);begin.setMax((int)sourceDuration);end.setMax((int)sourceDuration);begin.setProgress((int)c.optLong("start_ms"));end.setProgress((int)(c.optLong("start_ms")+c.optLong("duration_ms")));box.addView(MobileUi.text(this,"Début",12,MobileUi.MUTED));box.addView(begin);box.addView(MobileUi.text(this,"Fin",12,MobileUi.MUTED));box.addView(end);Runnable update=()->bounds.setText(time(begin.getProgress())+" → "+time(end.getProgress()));SeekBar.OnSeekBarChangeListener listener=new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar bar,int progress,boolean user){update.run();}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}};begin.setOnSeekBarChangeListener(listener);end.setOnSeekBarChangeListener(listener);update.run();
            AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Découper · "+name(path)).setView(box).setNegativeButton("Annuler",null).setNeutralButton("Tout le média",(d,n)->{remember();try{c.put("start_ms",0).put("duration_ms",sourceDuration);save();}catch(Exception e){toast(e.getMessage());}}).setPositiveButton("Appliquer",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{if(end.getProgress()-begin.getProgress()<500){toast("Garde au moins 0,5 seconde");return;}try{remember();c.put("start_ms",begin.getProgress()).put("duration_ms",end.getProgress()-begin.getProgress());save();dialog.dismiss();}catch(Exception e){toast(e.getMessage());}}));dialog.show();
        });}catch(Exception e){ui.post(()->toast(e.getMessage()));}});}
    private void filter(){String[] labels={"Original","Noir et blanc","Cinéma","Chaud","Froid","Contraste","Nuit","Vintage","Fondu noir 0,18 s","Retirer le fondu"};String[] keys={"aucun","noir","cinema","chaud","froid","contraste","nuit","vintage"};new AlertDialog.Builder(this).setTitle("Filtres du plan").setItems(labels,(d,n)->{if(n<8)put(clip(),"filter",keys[n]);else put(clip(),"fade_ms",n==8?180:0);}).show();}
    private void caption(){if(clip()==null)return;prompt("Texte du plan",clip().optString("text",""),text->put(clip(),"text",text));}
    private void speed(){new AlertDialog.Builder(this).setTitle("Vitesse du plan").setItems(new String[]{"0,25×","0,5×","1×","1,5×","2×","4×"},(d,n)->put(clip(),"speed",new double[]{.25,.5,1,1.5,2,4}[n])).show();}
    private void rotation(){new AlertDialog.Builder(this).setTitle("Rotation du plan").setItems(new String[]{"0°","90°","180°","−90°"},(d,n)->put(clip(),"rotation",new int[]{0,90,180,-90}[n])).show();}
    private void mute(){if(project==null)return;new AlertDialog.Builder(this).setTitle("Son").setItems(new String[]{"Conserver le son des vidéos","Couper le son des vidéos","Couper ce plan","Rétablir ce plan"},(d,n)->{if(n<2)put(project,"mute_original",n==1);else if(clip()!=null)put(clip(),"mute",n==2);}).show();}
    private void move(){new AlertDialog.Builder(this).setTitle("Déplacer le plan").setItems(new String[]{"Vers la gauche","Vers la droite"},(d,n)->{int to=selected+(n==0?-1:1);if(to<0||to>=clips().length())return;try{remember();Object a=clips().get(selected),b=clips().get(to);clips().put(selected,b);clips().put(to,a);selected=to;save();}catch(Exception ignored){}}).show();}
    private void duplicate(){try{remember();clips().put(new JSONObject(clip().toString()));save();}catch(Exception e){toast(e.getMessage());}}
    private void delete(boolean sound,int index){if(project==null||saving)return;try{remember();JSONArray src=sound?audio():clips(),out=new JSONArray();for(int i=0;i<src.length();i++)if(i!=index)out.put(src.get(i));project.put(sound?"audio":"clips",out);if(!sound&&out.length()==0)project.put("audio",new JSONArray());save();}catch(Exception e){toast(e.getMessage());}}
    private void ratioMenu(){if(project==null)return;String[] ratios={"source","9:16","16:9","1:1","4:3","3:4","4:5","2:1","2.35:1","custom"};new AlertDialog.Builder(this).setTitle("Format du montage").setItems(new String[]{"Original","9:16 · Téléphone","16:9 · Paysage","1:1 · Carré","4:3","3:4","4:5","2:1","2,35:1 · Cinéma","Ratio personnalisé"},(d,n)->{if(n==9)prompt("Largeur:hauteur","9:16",r->setRatio(r));else setRatio(ratios[n]);}).show();}
    private void setRatio(String ratio){new AlertDialog.Builder(this).setTitle("Adapter l’image").setItems(new String[]{"Tout conserver (bandes noires)","Remplir (recadrage centré)"},(d,n)->{try{remember();project.put("aspect_ratio",ratio).put("aspect_mode",n==0?"fit":"crop");save();}catch(Exception ignored){}}).show();}
    private void qualityMenu(){if(project==null||saving)return;new AlertDialog.Builder(this).setTitle("Qualité vidéo").setSingleChoiceItems(new String[]{"480p · Léger","720p · Standard","1080p · Haute définition"},project.optInt("resolution",720)==480?0:project.optInt("resolution",720)==720?1:2,(d,n)->{put(project,"resolution",new int[]{480,720,1080}[n]);d.dismiss();}).setNegativeButton("Fermer",null).show();}
    private void export(){
        if(project==null||saving||importing){toast("Attends la fin de l’importation ou de la sauvegarde");return;}if(clips().length()==0){toast("Ajoute une vidéo avant d’exporter");return;}
        String snapshot=project.toString();WorkspaceCommands.IO.execute(()->{try{JSONObject p=new JSONObject(snapshot);boolean exists=new WorkspaceStore(this).file(p.getString("output")).exists();ui.post(()->{if(!alive)return;String message=clips().length()+" plans · "+time(total())+"\n"+project.optInt("resolution",720)+"p · "+project.optString("aspect_ratio","source").replace("source","Original")+"\n"+name(project.optString("output"));
            if(exists)new AlertDialog.Builder(this).setTitle("Exporter le projet complet").setMessage(message+"\n\nUne vidéo porte déjà ce nom.").setNegativeButton("Annuler",null).setNeutralButton("Remplacer",(d,n)->startExport(true,false)).setPositiveButton("Nouvelle copie",(d,n)->startExport(false,true)).show();
            else new AlertDialog.Builder(this).setTitle("Exporter le projet complet").setMessage(message).setNegativeButton("Annuler",null).setPositiveButton("Exporter",(d,n)->startExport(false,false)).show();
        });}catch(Exception e){ui.post(()->toast(e.getMessage()));}});
    }
    private void startExport(boolean replace,boolean copy){
        if(saving||importing)return;saving=true;player.pause();
        try{JSONObject snapshot=new JSONObject(project.toString());if(copy){String path=snapshot.getString("output");snapshot.put("output",path.substring(0,path.length()-4)+"-"+System.currentTimeMillis()+".mp4");}
            engine.command(this,"video_editor_project_save",new JSONObjectSafe("project",snapshot).withRevision(revision),(ok,res)->ui.post(()->{saving=false;if(!alive)return;if(!ok){toast(res);return;}try{project=new JSONObject(res).getJSONObject("project");revision=project.optInt("revision");draw();engine.command(this,"video_editor_export",new JSONObject().put("replace",replace),(success,result)->ui.post(()->{if(!success&&alive)new AlertDialog.Builder(this).setTitle("Export impossible").setMessage(result).setPositiveButton("OK",null).show();}));}catch(Exception e){toast(e.getMessage());}}));
        }catch(Exception e){saving=false;toast(e.getMessage());}
    }
    private void outputMenu(){String s=engine.status().optString("state");if(s.equals("running")||s.equals("preparing")){new AlertDialog.Builder(this).setTitle("Export en cours").setMessage("Le rendu continue avec une notification sur le téléphone. Tu peux quitter cet écran.").setNegativeButton("Continuer",null).setPositiveButton("Annuler l’export",(d,n)->engine.command(this,"video_editor_cancel",new JSONObject(),(ok,res)->{})).show();return;}if(!s.equals("completed"))return;String output=engine.status().optString("output");new AlertDialog.Builder(this).setTitle("Montage complet prêt").setItems(new String[]{"Lire","Enregistrer sur le téléphone","Partager","Vérifier la durée et les pistes"},(d,n)->{try{WorkspaceStore store=new WorkspaceStore(this);if(n==0)startActivity(new Intent(this,MediaPreviewActivity.class).putExtra("path",output));else if(n==1){exportCopyPath=output;startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("video/mp4").putExtra(Intent.EXTRA_TITLE,name(output)),811);}else if(n==2)startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("video/mp4").putExtra(Intent.EXTRA_STREAM,store.uri(output)).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION),"Partager le montage"));else engine.command(this,"video_editor_verify_output",new JSONObject(),(ok,res)->ui.post(()->{if(!alive)return;try{JSONObject result=new JSONObject(res);new AlertDialog.Builder(this).setTitle(result.optBoolean("valid")?"Montage vérifié":"Vérification à reprendre").setMessage("Durée : "+time(result.optLong("duration_ms"))+"\nDurée attendue : "+time(result.optLong("expected_duration_ms"))+"\nVidéo : "+result.optString("width_px")+" × "+result.optString("height_px")+"\nAudio : "+(result.optBoolean("has_audio")?"présent":"absent")).setPositiveButton("OK",null).show();}catch(Exception e){toast(res);}}));}catch(Exception e){toast(e.getMessage());}}).show();}
    private interface TextResult{void done(String text);}
    private void prompt(String label,String initial,TextResult result){EditText e=new EditText(this);e.setText(initial);new AlertDialog.Builder(this).setTitle(label).setView(e).setNegativeButton("Annuler",null).setPositiveButton("Appliquer",(d,n)->result.done(e.getText().toString().trim())).show();}
    private void projectMenu(){if(project==null)return;new AlertDialog.Builder(this).setTitle("Projet").setItems(new String[]{"Renommer","Destination MP4","Nouveau montage","Sauvegarder une copie du projet","Ouvrir un projet JSON","Charger Alpha Omega"},(d,n)->{switch(n){case 0:prompt("Nom",project.optString("name"),t->put(project,"name",t));break;case 1:prompt("Destination dans Fichiers",project.optString("output"),t->put(project,"output",t));break;case 2:new AlertDialog.Builder(this).setTitle("Commencer un nouveau montage ?").setMessage("Conserve une copie avant de remplacer le projet actuel.").setNegativeButton("Annuler",null).setPositiveButton("Nouveau",(x,y)->{try{remember();project=new JSONObject().put("name","Nouveau montage").put("output","Montage-"+System.currentTimeMillis()+".mp4").put("clips",new JSONArray()).put("audio",new JSONArray());save();}catch(Exception ignored){}}).show();break;case 3:WorkspaceCommands.IO.execute(()->{try{new WorkspaceStore(this).writeText("Projet-"+System.currentTimeMillis()+".json",project.toString(2),false);ui.post(()->toast("Projet enregistré dans Fichiers"));}catch(Exception e){ui.post(()->toast(e.getMessage()));}});break;case 4:chooseFolder("project","",0);break;case 5:engine.command(this,"video_editor_preset_alpha_omega",new JSONObject(),(ok,res)->ui.post(()->{if(ok)engine.command(this,"video_editor_project_read",new JSONObject(),(yes,r)->ui.post(()->{try{project=new JSONObject(r);revision=project.optInt("revision");draw();preview();}catch(Exception ignored){}}));else toast(res);}));break;}}).show();}
    private void addMenu(String kind){if(project==null||saving||importing)return;importKind=kind;new AlertDialog.Builder(this).setTitle("Ajouter "+(kind.equals("video")?"une vidéo":"un audio")).setItems(new String[]{"Depuis le téléphone","Depuis Fichiers CHK"},(d,n)->{if(n==0)startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType(kind+"/*").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true),810);else chooseFolder(kind,"",0);}).show();}
    private void chooseFolder(String kind,String folder,int page){WorkspaceCommands.IO.execute(()->{try{WorkspaceStore store=new WorkspaceStore(this);JSONObject batch=store.list(folder,"",page);JSONArray rows=batch.getJSONArray("items");ArrayList<String> names=new ArrayList<>(),paths=new ArrayList<>();if(!folder.isEmpty()){names.add("‹ Parent");paths.add("..");}for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);String p=row.getString("path");if(row.getBoolean("directory")||kind.equals("project")&&p.endsWith(".json")||row.getString("mime_type").startsWith(kind+"/")){names.add((row.getBoolean("directory")?"▱ ":"")+row.getString("name"));paths.add(p);}}if(batch.optInt("next_offset",-1)>=0){names.add("Suite ›");paths.add("#next");}ui.post(()->{if(!alive)return;new AlertDialog.Builder(this).setTitle("Fichiers / "+folder).setItems(names.toArray(new String[0]),(d,n)->{String p=paths.get(n);if(p.equals(".."))chooseFolder(kind,folder.contains("/")?folder.substring(0,folder.lastIndexOf('/')):"",0);else if(p.equals("#next"))chooseFolder(kind,folder,page+50);else{try{if(store.file(p).isDirectory())chooseFolder(kind,p,0);else addFile(kind,p);}catch(Exception e){toast(e.getMessage());}}}).setNegativeButton("Fermer",null).show();});}catch(Exception e){ui.post(()->toast(e.getMessage()));}});}
    private void addFile(String kind,String path){if(saving||importing)return;WorkspaceCommands.IO.execute(()->{try{if(kind.equals("project")){WorkspaceStore store=new WorkspaceStore(this);StringBuilder body=new StringBuilder();int offset=0;do{JSONObject page=store.readText(path,offset);body.append(page.getString("text"));offset=page.getInt("next_offset");}while(offset>=0);String json=body.toString();ui.post(()->{try{remember();project=new JSONObject(json);save();}catch(Exception e){toast(e.getMessage());}});return;}JSONObject metadata=MediaInspection.info(this,path);long duration=metadata.optLong("duration_ms",0);if(duration<500)throw new Exception("Durée du média indisponible ou trop courte");ui.post(()->{try{remember();JSONObject c=new JSONObject().put("path",path).put("start_ms",0).put("duration_ms",duration);if(kind.equals("video"))clips().put(c);else{long remaining=total();for(int i=0;i<audio().length();i++)remaining-=audio().getJSONObject(i).optLong("duration_ms");if(remaining<500){toast("Ajoute une vidéo ou raccourcis l’audio précédent");return;}c.put("duration_ms",Math.min(duration,remaining));JSONArray a=audio();a.put(c);project.put("audio",a);}selected=clips().length()-1;save();}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){ui.post(()->toast(e.getMessage()));}});}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);
        if(request==811&&result==RESULT_OK&&data!=null&&data.getData()!=null){android.net.Uri target=data.getData();String path=exportCopyPath;WorkspaceCommands.IO.execute(()->{try(java.io.InputStream in=new java.io.FileInputStream(new WorkspaceStore(this).file(path));java.io.OutputStream out=getContentResolver().openOutputStream(target,"w")){if(out==null)throw new java.io.IOException("Destination indisponible");byte[] buffer=new byte[65536];int count;while((count=in.read(buffer))!=-1)out.write(buffer,0,count);ui.post(()->toast("Montage complet enregistré sur le téléphone"));}catch(Exception e){ui.post(()->toast(e.getMessage()));}});return;}
        if(request!=810||result!=RESULT_OK||data==null||project==null)return;String kind=importKind;ArrayList<android.net.Uri> uris=new ArrayList<>();if(data.getClipData()!=null)for(int i=0;i<Math.min(20,data.getClipData().getItemCount());i++)uris.add(data.getClipData().getItemAt(i).getUri());else if(data.getData()!=null)uris.add(data.getData());if(uris.isEmpty())return;importing=true;status.setText("Importation de "+uris.size()+" média(s)…");
        WorkspaceCommands.IO.execute(()->{JSONArray batch=new JSONArray();ArrayList<String> errors=new ArrayList<>();for(android.net.Uri uri:uris)try{String filename="Media-"+System.nanoTime();try(Cursor cursor=getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(cursor!=null&&cursor.moveToFirst())filename=cursor.getString(0);}WorkspaceStore store=new WorkspaceStore(this);if(store.file(filename).exists())filename=System.currentTimeMillis()+"-"+filename;store.importUri(uri,filename);long duration=MediaInspection.info(this,filename).optLong("duration_ms");if(duration<500)throw new Exception("Média trop court ou durée indisponible");batch.put(new JSONObject().put("path",filename).put("start_ms",0).put("duration_ms",duration));}catch(Exception e){errors.add(e.getMessage());}
            ui.post(()->{importing=false;if(!alive)return;if(batch.length()>0)try{remember();JSONArray target=kind.equals("video")?clips():audio();long remaining=total();for(int i=0;i<audio().length();i++)remaining-=audio().optJSONObject(i).optLong("duration_ms");for(int i=0;i<batch.length();i++){JSONObject c=batch.getJSONObject(i);if(kind.equals("audio")){if(remaining<500){errors.add("Audio supplémentaire ignoré : le montage vidéo est trop court");break;}long length=Math.min(c.getLong("duration_ms"),remaining);c.put("duration_ms",length);remaining-=length;}target.put(c);}if(kind.equals("audio"))project.put("audio",target);selected=clips().length()-1;save();}catch(Exception e){toast(e.getMessage());}if(!errors.isEmpty())new AlertDialog.Builder(this).setTitle("Importation à vérifier").setMessage(android.text.TextUtils.join("\n",errors)).setPositiveButton("OK",null).show();});
        });
    }
    @Override protected void onSaveInstanceState(Bundle state){super.onSaveInstanceState(state);state.putString("export_copy_path",exportCopyPath);}
    @Override protected void onPause(){if(player!=null){primingPreview=false;player.pause();player.setVolume(previewVolume);}super.onPause();}
    @Override protected void onDestroy(){alive=false;previewGeneration++;ui.removeCallbacksAndMessages(null);if(player!=null)player.release();super.onDestroy();}
    private static final class JSONObjectSafe extends JSONObject{JSONObjectSafe(String key,Object value){try{put(key,value);}catch(Exception ignored){}}JSONObjectSafe withRevision(int revision){try{put("expected_revision",revision);}catch(Exception ignored){}return this;}}
}
